// User-facing content components
export { ContentCard } from './ContentCard'
export { ContentGrid } from './ContentGrid'
export { WorkoutPlanCard } from './WorkoutPlanCard'
export { WorkoutPlanGrid } from './WorkoutPlanGrid'
export { ChallengeCard } from './ChallengeCard'
export { ChallengeGrid } from './ChallengeGrid'
export { FilterBar } from './FilterBar'
export { SearchBar } from './SearchBar'
export { PaginationControls } from './PaginationControls'
export { EmptyState } from './EmptyState'
export { LoadingGrid } from './LoadingGrid'
export { ChallengeFilters } from './ChallengeFilters'
export { LeaderboardTable } from './LeaderboardTable'
export { ChallengeProgress } from './ChallengeProgress'
export { XPChart } from './XPChart'
export { AchievementWall } from './AchievementWall'
export { StatsOverview } from './StatsOverview'
export { GoalTracker } from './GoalTracker'
export { ProfileHeader } from './ProfileHeader'
export { SettingsForm } from './SettingsForm'

// Previously created dashboard components
export { NeumorphicCard } from './NeumorphicCard'
export { XPRing } from './XPRing'
export { StatsCards } from './StatsCards'
export { BottomNavigation } from './BottomNavigation'
export { QuickActions } from './QuickActions'
export { TrainerApplicationBanner } from './TrainerApplicationBanner'
export { RecentActivity } from './RecentActivity'
export { Sidebar } from './Sidebar'
export { DesktopLayout } from './DesktopLayout'
export { LevelProgress } from './LevelProgress'
export { QuestCard } from './QuestCard'
export { AchievementCard } from './AchievementCard'
export { SummaryCard } from './SummaryCard'
export { MobileHeader } from './MobileHeader'

